steps:
    - id: "Test"
      name: "gcr.io/cloud-builders/go:alpine"
      args: ["test", "fcsum"]
      env: ["GOPATH=."]

    - id: "Build"
      name: "gcr.io/cloud-builders/go:alpine"
      args: ["build", "-o", "build/sum", "./src/fcsum"]
      env: ["GOPATH=."]

    - id: "Create image"
      name: "gcr.io/cloud-builders/docker"
      args:
          - "build"
          - "--tag=gcr.io/$PROJECT_ID/fc-sum-golang:latest"
          - "--tag=gcr.io/$PROJECT_ID/fc-sum-golang:1.0"
          - "--file=Dockerfile"
          - "."

images:
    - "gcr.io/$PROJECT_ID/fc-sum-golang:latest"
    - "gcr.io/$PROJECT_ID/fc-sum-golang:1.0"
